language: python

cache: pip

python:
  - "3.5"

install:
  - pip install --upgrade pip  # upgrading pip and install pyyaml first speeds up install significantly
  - pip install .
  - pip install -r requirements_test.txt

script:
  - flake8 aiohttp_runserver/ tests/
#  - py.test --cov=aiohttp_runserver

after_success:
  - coverage combine
  - codecov
